### ISSUE TITLE
Certificate error when visiting website

### ISSUE THREAD

**Issue by lisahillebrand** [heartsofcode/heartofcode#58]
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by rdwz** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by vsmart** [comment]
Should be fixed since this year! Please re-open if you are still seeing issues. thank you!
